# ===================================================================
# Spring Boot configuration for the "Cloud" profile.
# ===================================================================
security:
  user:
    password: user
spring:
  profiles:
      active: cloud
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  main:
    show_banner: false
server:
  port: 4567